### ISSUE TITLE
Copyright-Anmerkungen

### ISSUE THREAD

**Issue by JOOpdenhoevel** [ProjectL-Team/ProjectL#16]
Es geht um was Rechtliches: Wir nutzen ja die [GNU Public License](https://github.com/ProjectL-Team/ProjectL/blob/master/LICENSE) als rechtliche Grundlage für uns und unsere zukünftigen Nutzer, diese sieht allerdings vor, dass in jeder Quellcode-Datei eine Anmerkung zum Copyright vorhanden ist. Wir ihr zum Beispiel im [Core Modul](https://github.com/ProjectL-Team/ProjectL/blob/master/Source/EngineL/Core.py) sehen könnt, ist diese Notiz dort schon vorhanden. Bitte schreibt diese Notiz auch in jede andere Quellcode-Datei!

Für Python-Dateien sieht die so aus:

    """
    Beschreibung des Moduls.

    Copyright (C) 2017 Jan-Oliver "Janonard" Opdenhövel

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
    """

Ganz oben muss natürlich eine ganz kurze Beschreibung rein, was das Modul macht. In den Zeilen darunter steht genau, wer wann an der Datei mitgewirkt hat. Bei Jason gäbe es zum Beispiel noch die Zeile `Copyright (C) 2017 Jason "J2a0s0o0n" Becker`.

Bei den XML-Dateien sieht's so ähnlich, nur anders aus, da Kommentare in XML anders sind als in Python:

    

Bitte fügt bei allen Dateien, an denen ihr mitgewirkt habt, diese Notizen hinzu und stellt einen Pull Request!

**Comment by Flummi3** [comment]
Wieso geht das nur auf deinen Namen?

**Comment by JOOpdenhoevel** [comment]
Sorry, das ist ein Missverständniss: Ich habe meinen Namen nur als Beispiel genommen, natürlich soll Jeder genannt werden, der an der Datei mit gewirkt hat. In der [strings.xml](https://github.com/ProjectL-Team/ProjectL/blob/cfdd3f31be99f7d99d330c55fc12096b08ca7f18/Resources/strings.xml) meines Pullrequests sieht man das ganz gut: Da laut Git alle an der Datei mitgewirkt haben, hab ich auch von jedem einzelnen den Namen genannt.
