### ISSUE TITLE
Schöne Namen für die Wege

### ISSUE THREAD

**Issue by JOOpdenhoevel** [ProjectL-Team/ProjectL#25]
Aktuell heißt der Weg zwischen Ivys Hütte und dem Dorf noch **"Weg zwischen Ivys Hütte und dem Dorf"**, was zum Eingeben sehr unhandlich ist. Dazu kommt, dass der andere Weg dem entsprechend **"Weg zwischen dem Hafen und dem Dorf"** heißen müsste, was mindestens genauso unhandlich ist.

Ich bin gerade ein wenig am Testen und der Name nervt mich sehr, und wenn der Name schon Leute nervt, die relativ sicher tippen können. dann nervt er "Laien" nur umso mehr! Also: Die Wege brauchen andere Namen!

Für den Weg zum Hafen könnte ich "Hafenweg" vorschlagen, kurz und naheliegend. Bei Ivys Weg fällt mir da außer "Nordweg" oder "Müllhaldenweg" nichts besseres ein.

Wie sieht ihr das?

**Comment by jsonBackup** [comment]
Ich sehe das eigentlich genauso. Zudem finde ich auch den Namen des Ortes "Platz vor Ivys Hütte" etwas zu lang und zum Testen muss ich den Namen so gut wie jedes mal eingeben, bei Rechtschreibfehler öfters. Zudem hört sich "Vorgarten" meiner Meinung wesentlich besser an.

Allerdings muss der Spieler jeden Weg oder Ort nicht mehr als fünf mal eingeben, und vielleicht ist es für ihn gar nicht so nervig.

**Comment by Flummi3** [comment]
Wie gesagt könnte man für den Weg von Ivy zum Dorf einfach "Feldweg" benutzen. Das würde dann auch dazu passen, dass er größtenteils nur von ihr benutzt wird und dementsprechend relativ klein ist.

**Comment by JOOpdenhoevel** [comment]
Stimmt, oder "Trampelpfad".

Also, die Kandidaten sind:

- Weg zwischen Ivys Hütte und dem Dorf
  - Müllhaldenweg
  - Nordweg
  - Feldweg
  - Trampelpfad
- Weg zwischen dem Hafen und dem Dorf
  - Hafenweg
- Platz vor Ivys Hütte
  - Vorgarten

Seid ihr mit der Aufstellung einverstanden? Welchen von den vier Kandidaten wollen wir für den ersten Punkt nehmen?

**Comment by jsonBackup** [comment]
Ich bin einverstanden und stimme für den "Trampelpfad" und zwar aus dem Grund, da Ivy die einzige Person ist die ihn benutzt und ihn daher auch benannt haben muss. Ich finde das würde irgendwie ihren verträumten Charakter widerspiegeln.

**Comment by JOOpdenhoevel** [comment]
Macht einer von euch dann einen PR?
