### ISSUE TITLE
Kombination von nicht kombinierbaren Gegenständen führt zum Absturz

### ISSUE THREAD

**Issue by jsonBackup** [ProjectL-Team/ProjectL#29]
"Could not find a resource string with the key core.gameplayParser.genericError"

Diese Meldung tritt auf, wenn man zum Beispiel versucht den Ofen mit dem Toast zu kombinieren, obwohl der Ofen noch nicht an ist. Die on_used() Methode der Klasse "Ofen" gibt ein "False" zurück, da in diesem Fall self.get_state("on") != 0: 
Ein Absturz tritt also auch dann auf wenn ich die Marmelade mit dem Ofen oder Holz kombinieren will. 

Edit:
Sobald man sich in der Hütte befindet und "benutze Toast" engibt oder den Toast aufhebt und dann den Toast verwendet stürtzt das Programm ab.

**Comment by JOOpdenhoevel** [comment]
Ich kann den Fehler nicht nachvollziehen. Selbst auf deinem Zweig gibt das Spiel immer die Meldung, die es geben soll (z.B. "das geht nicht"). Es scheint so, als sei deine lokale Kopie auf deinem Rechner auf mehreren Ständen gleichzeitig. Mehr oder weniger vor kurzem habe ich die Fehlerausgaben überarbeitet und dabei den String "Das geht nicht!" mit dem Key "core.gameplayParser.genericError" erstellt. Jetzt scheint es aber so, als ob das Programm, also der Python-Code, auf dem aktuellen Stand ist, die strings.xml aber nicht. Ich muss mir das ganze mal in einem Skype-Anruf angucken, das ist ein interessantes Problem!

**Comment by JOOpdenhoevel** [comment]
Okay, das Problem ist jetzt klar und mittlerweile in 034e1d1 gefixt. Nur eine Bitte für den nächsten Bug: Als du diesen Issue aufgemacht hast, war die problematische Version von ProjectL für mich nicht verfügbar, da du deine Änderungen noch nicht hochgeladen hattest. Wenn du das nächste Mal so ein Problem hast, dann stell einfach einen Pull Request und beschreib dein Problem dort, weil ich dann weiß, welche Version gemeint ist.
