### ISSUE TITLE
Wiedergabe der Beschreibung nach der Statusänderung

### ISSUE THREAD

**Issue by JOOpdenhoevel** [ProjectL-Team/ProjectL#36]
Ich als Spiel fände es sehr angenehm, wenn ich auf Kombinationen u. ä. irgendwie eine Rückmeldung bekomme. Was haltet ihr davon, dass immer, wenn ein Status geändert wird, die Beschreibung des Gegenstandes ausgegeben wird? Natürlich könnte man diese Funktion auch für Einzelfälle abschalten (über einen Parameter mit Standartwert). Was haltet ihr davon?

**Comment by J2a0s0o0n** [comment]
Also ich finde die Idee gut, musst mir nur erklären wie man das umsetzt.

**Comment by jsonBackup** [comment]
Also ich finde die Idee gut, müsstest mir nur zeigen wie man das umsetzt.

**Comment by Flummi3** [comment]
Ja, ich glaube auch, dass das sinnvoll wäre.

**Comment by JOOpdenhoevel** [comment]
Okay, ich mach das später.

**Comment by JOOpdenhoevel** [comment]
Ehm, das ist doch eine Sache für euch: Die `set_state`-Methode, die ich verändern will, ist im `Core`-Modul, aber um irgendetwas auszugeben, muss man auf Funktionen des `Gameplay`-Modul aufrufen. Da allerdings schon `Gameplay` auf `Core` aufbaut, kann ich von `Core` aus nicht darauf zugreifen und daher auch nichts ausgeben.

Das heißt, dass nach jeder Statusänderung selbst auch die Ausgabe erfolgen muss. Zum Beispiel müsste `Jam.on_used` dann in etwa so lauten:

    def on_used(self, user, other_entity=None):
        """
        This non-constant, overriden method does something.
        """
        if isinstance(other_entity, Toast):
            if other_entity.get_state("toasted") == 1:
                other_entity.set_state("coated", 1)
                user.get_window().show_text(other_entity.get_raw_description()) # <- Die Ausgabe
                self.setParent(None)
                return True
            else:
                return False
        else:
            return False
