### ISSUE TITLE
Aufteilung der Spielabschnitte

### ISSUE THREAD

**Issue by JOOpdenhoevel** [ProjectL-Team/ProjectL#44]
Die Frage ist einfach: Wer macht was? Ich hab mal aufgeteilt, was noch benötigt wird:

1. Dorf 1 (Gespräch mit Ger)
2. Weg zum Hafen 1 (Gespräch mit Hex)
3. Hafen 1 (fehlgeleitete Suche nach der Kupferspule)
4. Dorf 2 (Suche nach einer Leiter)
5. Nutzfläche (Suchen der Leiterteile)
6. Berge (Suche nach dem Werkzeug, Öffnen der Quelle)
7. Dorf 3 (Wütende Bewohner)
8. Weg zum Hafen 2 (Freiräumen des Weges)
9. Hafen 2 (mitnehmen der Spule)
10. Dorf 4 (Blöde Kommentare)
11. Vorgarten (Aufbau des Windrades)
12. Epilog (Abschließende Szene)

Es gibt aber bei der Aufteilung mehrere Probleme. Ein Problem ist, dass einige Abschnitte von einander abhängig sind, zum Beispiel kann man erst die Interaktion "Windrad + Spule + Wegweiser" umsetzten, wenn die einzelnen Klassen schon vorhanden sind. Diese Abschnitte müssen daher nacheinander umgesetzt werden, außerdem können und müssen einzelne Abschnitte auch gemeinsam bearbeitet werden. Ebenfalls werden in jedem Abschnitt irgendwie Texte/Dialoge/Beschreibungen gebraucht; Wollen wir dann die Abschnitte einzeln mit Platzhaltern entwerfen, die dann von @Flummi3 ersetzt werden, oder schon von Anfang an mit den fertigen Texten arbeiten? Auch soll niemand zu viel oder zu wenig machen.

Wie sollten wir diese Probleme lösen? Ich fang am Besten schon mal mit Nummer 1 und 2 an, dann verlieren wir in der Diskussion keine Zeit.

**Comment by jsonBackup** [comment]
Ich wäre dafür, dass wir chronologisch vorgehen, heißt, dass wenn @Janonard Nummer 1 und 2 bearbeitet, wir uns als nächstes gemeinsam an Punkt 3 und 4 versuchen und so weiter, so ist es nicht zwangsläufig notwendig, dass die ganzen Texte jetzt schon fertig sein müssen und das Problem "Windrad + Spule + Wegweiser" würde so nicht auftreten.

**Comment by JOOpdenhoevel** [comment]
Okay, wird gemacht.

**Comment by JOOpdenhoevel** [comment]
1 und 2 sind fertig. Wenn @J2a0s0o0n Nummer 3 und 4 übernimmt, kann ich mich dann um 5 und 6 kümmern, okay?
