### ISSUE TITLE
Spielbericht

### ISSUE THREAD

**Issue by JOOpdenhoevel** [ProjectL-Team/ProjectL#55]
Hier ist ein Spielbericht, den ich am Wochende zusammen mit einem Freund erstellt habe:
Um das grobe vorweg zu nehmen: Er hat alles sofort gefunden, wobei die letzten Rätsel deutlich schwieriger waren als die Ersten, und das Spiel innerhalb von 30 Minuten durchgespielt. Die Dialoge und Beschreibungen, die bisher nur Platzhalter haben, musste ich ihm allerdings erklären. Einzelne Probleme sind mir bei den Tests aufgefallen, die ich hier zusammen mit einem Lösungsansatz aufliste. Über die einzelnen Punkte müssen wir noch diskutieren.

1. Nach seiner Aussage hat das Spiel Spaß gemacht, allerdings war es für ihn zuviel zu schreiben, unter anderem musste man zuviel hin- und hergehen. Die einzige passable Lösung wäre eine gute Autovervollständigung wie in einer Terminal-Konsole oder Markotasten. Bis zum Release lässt sich das allerdings nicht mehr umsetzen, das wäre dann etwas für nachträgliche Updates und Folgespiele.

2. Was sich allerdings noch umsetzen ließe, wäre eine Autocopy-Funktion, dass man mit den Pfeiltasten nach oben und unten durch die schon eingegebenen Befehle durchsuchen kann.

3. Es würde auch helfen, wenn der Text nach einem Dialog wieder nach unten gescrollt wird, ich probiere, ob ich das hin bekomme.

4. Auch ist es wiedersinning, dass man mit den Häusern "sprechen" muss, obwohl der Universalbefehl ja "benutze" ist. Das sollte, aus meiner Sicht, geändert werden.

5. Im README fehlt der Hinweis, dass man sich auch den Ort ansehen kann und an einer Stelle steht statt "Gerrit" "Alex".

6. Zeitweise wusste der Testspieler nicht mehr, an welchem Ort er sich befindet, hier würde es helfen, den Namen des Ortes in den Titel des Fensters zu stellen.

7. Das Minispiel könnte bessere Hinweise vertragen, was man als nächstes machen soll bzw. wenn etwas despawnt und so weiter.

8. Der Text könnte etwas größer dargestellt werden. Der Testspieler musste mehrfach näher an den Bildschirm heran, um den Text vernünftig lesen zu können.

9. Alter und unnötiger Text hat sehr schnell den Bildschirm gefüllt und das wiederfinden von Informationen erschwert. Eine Änderung, die das Verbessern könnte wäre, dass unnötiger Text einfach irgendwann verschwindet. Wo da allerdings der Übergang gemacht wird, ist schwierig zu entscheiden und daher eher was für später.

**Comment by jsonBackup** [comment]
Ich kann mich den ganzen Punkten nur anschließen. Mich persönlich hat es beim Spielen gestört, wenn man sich an einem Ort umsieht, und der Text "da ist Ivy" erscheint. Ich finde, dass dies teilweise überhaupt nicht zur Beschreibung passte, z.B.: "Mein Alkoven... Da ist ... Ivy". Schließlich ist der Erzähler Ivy und keine dritte Person.

Auch fände ich es noch gelungener, wenn das Spiel nicht mit der Beschreibung des Alkovens beginnt.

**Comment by JOOpdenhoevel** [comment]
Also muss Ivy "unsichtbar" werden, okay, ich setz mich dran.

Nur wie soll das Spiel anders anfangen?

**Comment by jsonBackup** [comment]
Ein Prolog dürfte meiner Meinung nach nicht fehlen. In ihm könnte Ivy anfangen etwas über sich zu erzählen, das nicht beim Betrachten des Spiegels bereits aufgenommen wurde. Ich hab überlegt, dass das wie ein Dialog im Fenster erscheint, also verzögert und nicht, dass der Spieler das Spiel startet und alles sofort statisch ist. Zudem könnte im Prolog nebenlüfig die Insel von ihr beschrieben werden und der Spieler darauf hingewiesen werden, dass Ivy gerne etwas zum Frühstück hätte. 
Außerdem weiß ich nicht, ob wir vielleicht Details vergessen haben, die wir in der [Handlung](https://docs.google.com/document/d/1gzYwgD53iXgn4FcL1REmJ61dx33YA6HRedOBpWv93hY/edit?ts=58d27f20) berücksichtigen wollten. Diese wären dann im Prolog einzubringen.
