### ISSUE TITLE
Bug bei dem die Quelle ein zweites Mal geöffnet wird.

### ISSUE THREAD

**Issue by Flummi3** [ProjectL-Team/ProjectL#58]
Wenn man nach dem Minispiel am Hafenweg das Werkzeug mit der wackeligen Leiter kombiniert, wird die Quelle erneut geöffnet und der Hafenweg wird wieder durch einen großen Haufen versperrt.

**Comment by JOOpdenhoevel** [comment]
Du bist etwas spät. Für den Bug gibt es schon einen Patch: #57

**Comment by Flummi3** [comment]
Wow. Oops
